### ISSUE TITLE
lock etcd : panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by firetaker** [micro/go-sync#4]
see title
panic: assignment to entry in nil map

_goroutine 1 [running]:
github.com/micro/go-sync/lock/etcd.(*etcdLock).Acquire(0xc042026540, 0xa2776b, 0x2, 0xc042004628, 0x1, 0x1, 0x2, 0x986e40)
	F:/goworks/src/github.com/micro/go-sync/lock/etcd/etcd.go:59 +0x378
main.main()
	F:/goworks/src/golearn/gosyncHowTo/lock_howto.go:35 +0x1ae_

**Comment by firetaker** [comment]
`return &etcdLock{
		path:   "/micro/lock",
		client: c,
		opts:   options,
		locks:make(map[string]*elock), // add this line will fix this issue
	}`

**Comment by asim** [comment]
Fixed
